# -*- coding: utf-8 -*-
"""coding_03_05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cxjNvL5W22GPLW81aZ90kXchyJ7ebii-

# **Spiral Matrix**
"""

def spiral(m,n,a):
  k = 0
  l = 0

  while(k<m and l<n):
    for i in range(l,n):
      print(a[k][i], end = " ")
    k+=1

    for i in range(k,m):
      print(a[i][n-1], end=" ")
    n-=1

    for i in range(n-1,l-1,-1):
      print(a[m-1][i], end = " ")
    m -=1

    for i in range(m-1,k-1,-1):
      print(a[i][l], end = " ")
    l+=1

a = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12],
     [13, 14, 15, 16]]

row = 4
col = 4
spiral(row,col,a)

"""# **ADDITION OF ODD INDEX ELEMENT IN THE ARRAY**"""

list = [1,2,3,4,5,6,7]
s = 0
k = -1
for i in list:
  k = k+1
  if(k%2==0):
     continue
  else:
    s=s+i
print(s)

"""# **SUB ARRAY SUM**"""

def sub_array(list):
  s = 0
  a = []
  for i in list:
    if sum(i) > s:
      s = sum(i)
      a = i
  return (s,a)

sub_array([ [1,2,3],[4,5,6,], [7,8,9,]])

"""# **KADANE ALGORITHM (Largest Sum Contiguous Subarray)**"""

def GFG(a, size):
    max = float('-inf')
    max_ending = 0
    for i in range(0, size):
        max_ending = max_ending + a[i]
        if max < max_ending:
            max= max_ending
        if max_ending< 0:
            max_ending= 0
    return max
# Driver function to check the above function
a = [-2, -3, 4, -1, -2, 1, 5, -3]
print("Maximum contiguous sum is", GFG(a, len(a)))

"""# **REDUCED SUBTRACTION**

# **FREQUENCY OF THE ARRAY**
"""

def countFrequency(arr, size):
    for i in range(0, size):
        flag = False
        count = 0
        for j in range(i+1, size):
            if arr[i] == arr[j]:
                flag = True
                break
        if flag == True:
            continue
        for j in range(0, i+1):
            if arr[i] == arr[j]:
                count += 1
        print("{0}: {1}".format(arr[i], count))
arr = [5, 8, 5, 7, 8, 10]
n = len(arr)
countFrequency(arr , n)

"""# **TRANPOSE OF MATRIX**"""

X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[0,0,0],
         [0,0,0]]

for i in range(len(X)):
   for j in range(len(X[0])):
       result[j][i] = X[i][j]

for r in result:
   print(r)

"""# **PRINT NEGATIVE ELEMENT IN ARRAY**"""

list1 = [11, -21, 0, 45, 66, -93]
for num in list1:
    if num < 0:
        print(num,end=" ")