# -*- coding: utf-8 -*-
"""Copy of coding/02/05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dtqk1OE5vEegA7qGvsgGB1947S3F-Wij

# **UNIQUE ELEMENT IN ARRAY**
"""

number = {1,2,3,4,3,5,2}
ans = []
for i in number:
  if i not in ans:
    ans.append(i)
print(ans)

"""# **Duplicate element in array**"""

lis = [1, 2, 1, 2, 3, 4, 5, 1, 1, 2, 5, 6, 7, 8, 9, 9]
uniqueList = []
duplicateList = []
for i in lis:
    if i not in uniqueList:
        uniqueList.append(i)
    elif i not in duplicateList:
        duplicateList.append(i)

print(duplicateList)
print(uniqueList)

"""# **second largest element in arr**"""

arr = [13,4,23,6]
arr.sort()
print(arr[-2])

"""# **Reversing the array**"""

rev = arr[::-1]
print(rev)

"""# **Rotate the array by one place**"""

arry = [1, 3, 5, 7, 9, 11, 13, 15]
E = 4
N = 8
def rotate_List1(arry, E, K):
  arry[:] = arry[E:K] + arry[0:E]
  return arry
arry = [11, 12, 13, 14, 15, 16, 17, 18]
print ("The List is: ", arry)
print ("The rotated list is: ")
print (rotate_List1(arry, 4, len(arry)))

"""# **splitting aphabet, numbers and special character separately**"""

str = "geeks01$$for02geeks03!@!!"
alpha = ""
num = ""
special = ""
for i in range(len(str)):
		if (str[i].isdigit()):
			num = num+ str[i]
		elif((str[i] >= 'A' and str[i] <= 'Z') or
			(str[i] >= 'a' and str[i] <= 'z')):
			alpha += str[i]
		else:
			special += str[i]
print(alpha)
print(num )
print(special)